// Next
import Head from "next/head";
import { Inter } from "next/font/google";
// Modules Components
import { LandingPage } from "modules/sales/capture/components/landing-page";
import { CoockiesPolicy } from "common/components/coockies-policy";
import './Global.css'


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
      <CoockiesPolicy />
      <div id='hamburger-nav-menu'></div>
    </>
  );
}
